// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *movies → gender*
 */
export interface MoviesDocumentDataGenderItem {
  /**
   * type field in *movies → gender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.gender[].type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;
}

/**
 * Item in *movies → production*
 */
export interface MoviesDocumentDataProductionItem {
  /**
   * name field in *movies → production*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.production[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * role field in *movies → production*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.production[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;
}

type MoviesDocumentDataSlicesSlice = never;

/**
 * Content for movies documents
 */
interface MoviesDocumentData {
  /**
   * title field in *movies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * plot field in *movies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.plot
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plot: prismic.KeyTextField;

  /**
   * gender field in *movies*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.gender[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gender: prismic.GroupField<Simplify<MoviesDocumentDataGenderItem>>;

  /**
   * review field in *movies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.review
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review: prismic.KeyTextField;

  /**
   * year field in *movies*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year: prismic.NumberField;

  /**
   * poster field in *movies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.poster
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;

  /**
   * background field in *movies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * main_color field in *movies*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.main_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  main_color: prismic.ColorField;

  /**
   * runtime field in *movies*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.runtime
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  runtime: prismic.NumberField;

  /**
   * parental_rating field in *movies*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.parental_rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  parental_rating: prismic.NumberField;

  /**
   * production field in *movies*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.production[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  production: prismic.GroupField<Simplify<MoviesDocumentDataProductionItem>>;

  /**
   * trailer field in *movies*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.trailer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trailer: prismic.LinkField;

  /**
   * video field in *movies*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;

  /**
   * iframe field in *movies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.iframe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iframe: prismic.KeyTextField;

  /**
   * Slice Zone field in *movies*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MoviesDocumentDataSlicesSlice>
  /**
   * Meta Description field in *movies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: movies.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *movies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: movies.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *movies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: movies.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * movies document from Prismic
 *
 * - **API ID**: `movies`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MoviesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<MoviesDocumentData>, "movies", Lang>;

export type AllDocumentTypes = MoviesDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type { MoviesDocument, MoviesDocumentData, AllDocumentTypes };
  }
}
