import { SignatureButton } from '@/components/SignatureButton'
import { useSignatureContext } from '@/context/SignatureContext'
import { api } from '@/services/api'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'

interface SignatureResponse {
  signature: string | null;
}

export default function Home() {
  const { setSignature } = useSignatureContext();
  useEffect(() => {
    api.get<SignatureResponse>("/get-user-signature")
    .then((response) => {
      setSignature<string | null>(response.data.signature)
    })
   
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-[calc(100vh-4rem)] bg-home bg-cover bg-no-repeat'>
        <div className="h-full [background:linear-gradient(135deg,_#1E1E1E_35.16%,_#1E1E1E2f_100%)]    py-32 px-3">
            <section className='container'>
              <div className='max-w-2xl flex flex-col gap-2 '>
                  <h1 className='font-display font-black text-white text-[4rem] leading-[4rem]'>
                    <strong className='text-red-500'>Filmes</strong>  para todas as pessoas<strong className='text-red-500'>.</strong>
                  </h1>
                  <h2 className='text-white text-3xl'>
                    Assista a qualquer filme, em qualquer lugar
                    por apenas <strong className='font-display text-red-500 font-bold'>R$ 19,99</strong> 
                  </h2>
                  <SignatureButton />
              </div>
            </section>
          </div>
    </main>
    </>
  )
}
